# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Whether to push the image to the registry'
        required: true
        default: 'false'
      include_latest_tag:
        description: 'Whether to also tag the image as "latest"'
        required: true
        default: 'false'

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bitnami/mongodb/8.0/debian-12/

    env:
      IMAGE_NAME: andywebservices/mongodb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # B2 backend keys
          DOCKERHUB_USERNAME: "op://aws-svcs/iga3xtu2bg4b7ofi24qkaohaye/username"
          DOCKERHUB_TOKEN: "op://aws-svcs/iga3xtu2bg4b7ofi24qkaohaye/credential"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Extract version from Dockerfile
        id: version
        run: |
          VERSION=$(sed -n 's/org.opencontainers.image.version="\([^"]*\)"/\1/p' Dockerfile | xargs)
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      # Push = false for other triggers
      - name: Test build
        uses: docker/build-push-action@v6
        with:
          context: bitnami/mongodb/8.0/debian-12/
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}

      - name: Build and optionally push image
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: bitnami/mongodb/8.0/debian-12/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event.inputs.push_image == 'true' }}
          tags: >-
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}${{
              github.event.inputs.include_latest_tag == 'true' && '
            ' }}${{
              github.event.inputs.include_latest_tag == 'true' && env.IMAGE_NAME }}:latest



